package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
)

const OutFile = "template.gen.go"

func chkfatal(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	src, err := ioutil.ReadFile("sandstorm-pkgdef.capnp.template")
	chkfatal(err)
	dest, err := os.Create(OutFile)
	chkfatal(err)
	_, err = fmt.Fprintf(
		dest,
		`
		// This file was auto-generated by ./internal/embed-template.go.
		// DO NOT EDIT.

		package spk

		import "text/template"

		var pkgdefTemplate = template.Must(template.New("pkgdef").Parse(%q))
		`,
		src,
	)
	chkfatal(err)
	dest.Close()
	chkfatal(exec.Command("gofmt", "-w", OutFile).Run())
}
