// Code generated by capnpc-go. DO NOT EDIT.

package sandstormhttpbridge

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	grain "zenhack.net/go/sandstorm/capnp/grain"
	identity "zenhack.net/go/sandstorm/capnp/identity"
	powerbox "zenhack.net/go/sandstorm/capnp/powerbox"
)

type SandstormHttpBridge capnp.Client

// SandstormHttpBridge_TypeID is the unique identifier for the type SandstormHttpBridge.
const SandstormHttpBridge_TypeID = 0xad678f0d09bdd98a

func (c SandstormHttpBridge) GetSandstormApi(ctx context.Context, params func(SandstormHttpBridge_getSandstormApi_Params) error) (SandstormHttpBridge_getSandstormApi_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSandstormApi",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSandstormApi_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_getSandstormApi_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSessionContext(ctx context.Context, params func(SandstormHttpBridge_getSessionContext_Params) error) (SandstormHttpBridge_getSessionContext_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionContext",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSessionContext_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_getSessionContext_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSavedIdentity(ctx context.Context, params func(SandstormHttpBridge_getSavedIdentity_Params) error) (SandstormHttpBridge_getSavedIdentity_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSavedIdentity",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSavedIdentity_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_getSavedIdentity_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) SaveIdentity(ctx context.Context, params func(SandstormHttpBridge_saveIdentity_Params) error) (SandstormHttpBridge_saveIdentity_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      3,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "saveIdentity",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_saveIdentity_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_saveIdentity_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSessionRequest(ctx context.Context, params func(SandstormHttpBridge_getSessionRequest_Params) error) (SandstormHttpBridge_getSessionRequest_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      4,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionRequest",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSessionRequest_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_getSessionRequest_Results_Future{Future: ans.Future()}, release
}
func (c SandstormHttpBridge) GetSessionOffer(ctx context.Context, params func(SandstormHttpBridge_getSessionOffer_Params) error) (SandstormHttpBridge_getSessionOffer_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      5,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionOffer",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SandstormHttpBridge_getSessionOffer_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SandstormHttpBridge_getSessionOffer_Results_Future{Future: ans.Future()}, release
}

func (c SandstormHttpBridge) AddRef() SandstormHttpBridge {
	return SandstormHttpBridge(capnp.Client(c).AddRef())
}

func (c SandstormHttpBridge) Release() {
	capnp.Client(c).Release()
}

func (c SandstormHttpBridge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (SandstormHttpBridge) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge {
	return SandstormHttpBridge(capnp.Client{}.DecodeFromPtr(p))
}

func (c SandstormHttpBridge) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A SandstormHttpBridge_Server is a SandstormHttpBridge with a local implementation.
type SandstormHttpBridge_Server interface {
	GetSandstormApi(context.Context, SandstormHttpBridge_getSandstormApi) error

	GetSessionContext(context.Context, SandstormHttpBridge_getSessionContext) error

	GetSavedIdentity(context.Context, SandstormHttpBridge_getSavedIdentity) error

	SaveIdentity(context.Context, SandstormHttpBridge_saveIdentity) error

	GetSessionRequest(context.Context, SandstormHttpBridge_getSessionRequest) error

	GetSessionOffer(context.Context, SandstormHttpBridge_getSessionOffer) error
}

// SandstormHttpBridge_NewServer creates a new Server from an implementation of SandstormHttpBridge_Server.
func SandstormHttpBridge_NewServer(s SandstormHttpBridge_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(SandstormHttpBridge_Methods(nil, s), s, c)
}

// SandstormHttpBridge_ServerToClient creates a new Client from an implementation of SandstormHttpBridge_Server.
// The caller is responsible for calling Release on the returned Client.
func SandstormHttpBridge_ServerToClient(s SandstormHttpBridge_Server) SandstormHttpBridge {
	return SandstormHttpBridge(capnp.NewClient(SandstormHttpBridge_NewServer(s)))
}

// SandstormHttpBridge_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func SandstormHttpBridge_Methods(methods []server.Method, s SandstormHttpBridge_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 6)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSandstormApi",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSandstormApi(ctx, SandstormHttpBridge_getSandstormApi{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionContext",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSessionContext(ctx, SandstormHttpBridge_getSessionContext{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSavedIdentity",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSavedIdentity(ctx, SandstormHttpBridge_getSavedIdentity{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      3,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "saveIdentity",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.SaveIdentity(ctx, SandstormHttpBridge_saveIdentity{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      4,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionRequest",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSessionRequest(ctx, SandstormHttpBridge_getSessionRequest{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xad678f0d09bdd98a,
			MethodID:      5,
			InterfaceName: "sandstorm-http-bridge.capnp:SandstormHttpBridge",
			MethodName:    "getSessionOffer",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetSessionOffer(ctx, SandstormHttpBridge_getSessionOffer{call})
		},
	})

	return methods
}

// SandstormHttpBridge_getSandstormApi holds the state for a server call to SandstormHttpBridge.getSandstormApi.
// See server.Call for documentation.
type SandstormHttpBridge_getSandstormApi struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSandstormApi) Args() SandstormHttpBridge_getSandstormApi_Params {
	return SandstormHttpBridge_getSandstormApi_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSandstormApi) AllocResults() (SandstormHttpBridge_getSandstormApi_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results(r), err
}

// SandstormHttpBridge_getSessionContext holds the state for a server call to SandstormHttpBridge.getSessionContext.
// See server.Call for documentation.
type SandstormHttpBridge_getSessionContext struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSessionContext) Args() SandstormHttpBridge_getSessionContext_Params {
	return SandstormHttpBridge_getSessionContext_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSessionContext) AllocResults() (SandstormHttpBridge_getSessionContext_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results(r), err
}

// SandstormHttpBridge_getSavedIdentity holds the state for a server call to SandstormHttpBridge.getSavedIdentity.
// See server.Call for documentation.
type SandstormHttpBridge_getSavedIdentity struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSavedIdentity) Args() SandstormHttpBridge_getSavedIdentity_Params {
	return SandstormHttpBridge_getSavedIdentity_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSavedIdentity) AllocResults() (SandstormHttpBridge_getSavedIdentity_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results(r), err
}

// SandstormHttpBridge_saveIdentity holds the state for a server call to SandstormHttpBridge.saveIdentity.
// See server.Call for documentation.
type SandstormHttpBridge_saveIdentity struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_saveIdentity) Args() SandstormHttpBridge_saveIdentity_Params {
	return SandstormHttpBridge_saveIdentity_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_saveIdentity) AllocResults() (SandstormHttpBridge_saveIdentity_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results(r), err
}

// SandstormHttpBridge_getSessionRequest holds the state for a server call to SandstormHttpBridge.getSessionRequest.
// See server.Call for documentation.
type SandstormHttpBridge_getSessionRequest struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSessionRequest) Args() SandstormHttpBridge_getSessionRequest_Params {
	return SandstormHttpBridge_getSessionRequest_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSessionRequest) AllocResults() (SandstormHttpBridge_getSessionRequest_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionRequest_Results(r), err
}

// SandstormHttpBridge_getSessionOffer holds the state for a server call to SandstormHttpBridge.getSessionOffer.
// See server.Call for documentation.
type SandstormHttpBridge_getSessionOffer struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SandstormHttpBridge_getSessionOffer) Args() SandstormHttpBridge_getSessionOffer_Params {
	return SandstormHttpBridge_getSessionOffer_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SandstormHttpBridge_getSessionOffer) AllocResults() (SandstormHttpBridge_getSessionOffer_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SandstormHttpBridge_getSessionOffer_Results(r), err
}

// SandstormHttpBridge_List is a list of SandstormHttpBridge.
type SandstormHttpBridge_List = capnp.CapList[SandstormHttpBridge]

// NewSandstormHttpBridge creates a new list of SandstormHttpBridge.
func NewSandstormHttpBridge_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[SandstormHttpBridge](l), err
}

type SandstormHttpBridge_getSandstormApi_Params capnp.Struct

// SandstormHttpBridge_getSandstormApi_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSandstormApi_Params.
const SandstormHttpBridge_getSandstormApi_Params_TypeID = 0x86d490c59f64c564

func NewSandstormHttpBridge_getSandstormApi_Params(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_getSandstormApi_Params(st), err
}

func NewRootSandstormHttpBridge_getSandstormApi_Params(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_getSandstormApi_Params(st), err
}

func ReadRootSandstormHttpBridge_getSandstormApi_Params(msg *capnp.Message) (SandstormHttpBridge_getSandstormApi_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSandstormApi_Params(root.Struct()), err
}

func (s SandstormHttpBridge_getSandstormApi_Params) String() string {
	str, _ := text.Marshal(0x86d490c59f64c564, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSandstormApi_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSandstormApi_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSandstormApi_Params {
	return SandstormHttpBridge_getSandstormApi_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSandstormApi_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSandstormApi_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSandstormApi_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSandstormApi_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// SandstormHttpBridge_getSandstormApi_Params_List is a list of SandstormHttpBridge_getSandstormApi_Params.
type SandstormHttpBridge_getSandstormApi_Params_List = capnp.StructList[SandstormHttpBridge_getSandstormApi_Params]

// NewSandstormHttpBridge_getSandstormApi_Params creates a new list of SandstormHttpBridge_getSandstormApi_Params.
func NewSandstormHttpBridge_getSandstormApi_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSandstormApi_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[SandstormHttpBridge_getSandstormApi_Params](l), err
}

// SandstormHttpBridge_getSandstormApi_Params_Future is a wrapper for a SandstormHttpBridge_getSandstormApi_Params promised by a client call.
type SandstormHttpBridge_getSandstormApi_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSandstormApi_Params_Future) Struct() (SandstormHttpBridge_getSandstormApi_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSandstormApi_Params(s), err
}

type SandstormHttpBridge_getSandstormApi_Results capnp.Struct

// SandstormHttpBridge_getSandstormApi_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSandstormApi_Results.
const SandstormHttpBridge_getSandstormApi_Results_TypeID = 0xc174fe273bd649ac

func NewSandstormHttpBridge_getSandstormApi_Results(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results(st), err
}

func NewRootSandstormHttpBridge_getSandstormApi_Results(s *capnp.Segment) (SandstormHttpBridge_getSandstormApi_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSandstormApi_Results(st), err
}

func ReadRootSandstormHttpBridge_getSandstormApi_Results(msg *capnp.Message) (SandstormHttpBridge_getSandstormApi_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSandstormApi_Results(root.Struct()), err
}

func (s SandstormHttpBridge_getSandstormApi_Results) String() string {
	str, _ := text.Marshal(0xc174fe273bd649ac, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSandstormApi_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSandstormApi_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSandstormApi_Results {
	return SandstormHttpBridge_getSandstormApi_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSandstormApi_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSandstormApi_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSandstormApi_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSandstormApi_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSandstormApi_Results) Api() grain.SandstormApi {
	p, _ := capnp.Struct(s).Ptr(0)
	return grain.SandstormApi(p.Interface().Client())
}

func (s SandstormHttpBridge_getSandstormApi_Results) HasApi() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSandstormApi_Results) SetApi(v grain.SandstormApi) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSandstormApi_Results_List is a list of SandstormHttpBridge_getSandstormApi_Results.
type SandstormHttpBridge_getSandstormApi_Results_List = capnp.StructList[SandstormHttpBridge_getSandstormApi_Results]

// NewSandstormHttpBridge_getSandstormApi_Results creates a new list of SandstormHttpBridge_getSandstormApi_Results.
func NewSandstormHttpBridge_getSandstormApi_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSandstormApi_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSandstormApi_Results](l), err
}

// SandstormHttpBridge_getSandstormApi_Results_Future is a wrapper for a SandstormHttpBridge_getSandstormApi_Results promised by a client call.
type SandstormHttpBridge_getSandstormApi_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSandstormApi_Results_Future) Struct() (SandstormHttpBridge_getSandstormApi_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSandstormApi_Results(s), err
}

func (p SandstormHttpBridge_getSandstormApi_Results_Future) Api() grain.SandstormApi {
	return grain.SandstormApi(p.Future.Field(0, nil).Client())
}

type SandstormHttpBridge_getSessionContext_Params capnp.Struct

// SandstormHttpBridge_getSessionContext_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionContext_Params.
const SandstormHttpBridge_getSessionContext_Params_TypeID = 0xc2a480fa3863a3fa

func NewSandstormHttpBridge_getSessionContext_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Params(st), err
}

func NewRootSandstormHttpBridge_getSessionContext_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Params(st), err
}

func ReadRootSandstormHttpBridge_getSessionContext_Params(msg *capnp.Message) (SandstormHttpBridge_getSessionContext_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionContext_Params(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionContext_Params) String() string {
	str, _ := text.Marshal(0xc2a480fa3863a3fa, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionContext_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionContext_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionContext_Params {
	return SandstormHttpBridge_getSessionContext_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionContext_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionContext_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionContext_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionContext_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionContext_Params) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSessionContext_Params) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionContext_Params) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSessionContext_Params) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// SandstormHttpBridge_getSessionContext_Params_List is a list of SandstormHttpBridge_getSessionContext_Params.
type SandstormHttpBridge_getSessionContext_Params_List = capnp.StructList[SandstormHttpBridge_getSessionContext_Params]

// NewSandstormHttpBridge_getSessionContext_Params creates a new list of SandstormHttpBridge_getSessionContext_Params.
func NewSandstormHttpBridge_getSessionContext_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionContext_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionContext_Params](l), err
}

// SandstormHttpBridge_getSessionContext_Params_Future is a wrapper for a SandstormHttpBridge_getSessionContext_Params promised by a client call.
type SandstormHttpBridge_getSessionContext_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionContext_Params_Future) Struct() (SandstormHttpBridge_getSessionContext_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionContext_Params(s), err
}

type SandstormHttpBridge_getSessionContext_Results capnp.Struct

// SandstormHttpBridge_getSessionContext_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionContext_Results.
const SandstormHttpBridge_getSessionContext_Results_TypeID = 0xb84ffa3322e48dbd

func NewSandstormHttpBridge_getSessionContext_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results(st), err
}

func NewRootSandstormHttpBridge_getSessionContext_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionContext_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionContext_Results(st), err
}

func ReadRootSandstormHttpBridge_getSessionContext_Results(msg *capnp.Message) (SandstormHttpBridge_getSessionContext_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionContext_Results(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionContext_Results) String() string {
	str, _ := text.Marshal(0xb84ffa3322e48dbd, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionContext_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionContext_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionContext_Results {
	return SandstormHttpBridge_getSessionContext_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionContext_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionContext_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionContext_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionContext_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionContext_Results) Context() grain.SessionContext {
	p, _ := capnp.Struct(s).Ptr(0)
	return grain.SessionContext(p.Interface().Client())
}

func (s SandstormHttpBridge_getSessionContext_Results) HasContext() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionContext_Results) SetContext(v grain.SessionContext) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSessionContext_Results_List is a list of SandstormHttpBridge_getSessionContext_Results.
type SandstormHttpBridge_getSessionContext_Results_List = capnp.StructList[SandstormHttpBridge_getSessionContext_Results]

// NewSandstormHttpBridge_getSessionContext_Results creates a new list of SandstormHttpBridge_getSessionContext_Results.
func NewSandstormHttpBridge_getSessionContext_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionContext_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionContext_Results](l), err
}

// SandstormHttpBridge_getSessionContext_Results_Future is a wrapper for a SandstormHttpBridge_getSessionContext_Results promised by a client call.
type SandstormHttpBridge_getSessionContext_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionContext_Results_Future) Struct() (SandstormHttpBridge_getSessionContext_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionContext_Results(s), err
}

func (p SandstormHttpBridge_getSessionContext_Results_Future) Context() grain.SessionContext {
	return grain.SessionContext(p.Future.Field(0, nil).Client())
}

type SandstormHttpBridge_getSavedIdentity_Params capnp.Struct

// SandstormHttpBridge_getSavedIdentity_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSavedIdentity_Params.
const SandstormHttpBridge_getSavedIdentity_Params_TypeID = 0x930d8201947c86bf

func NewSandstormHttpBridge_getSavedIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Params(st), err
}

func NewRootSandstormHttpBridge_getSavedIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Params(st), err
}

func ReadRootSandstormHttpBridge_getSavedIdentity_Params(msg *capnp.Message) (SandstormHttpBridge_getSavedIdentity_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSavedIdentity_Params(root.Struct()), err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) String() string {
	str, _ := text.Marshal(0x930d8201947c86bf, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSavedIdentity_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSavedIdentity_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSavedIdentity_Params {
	return SandstormHttpBridge_getSavedIdentity_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSavedIdentity_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSavedIdentity_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSavedIdentity_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSavedIdentity_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSavedIdentity_Params) IdentityId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) HasIdentityId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSavedIdentity_Params) IdentityIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSavedIdentity_Params) SetIdentityId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// SandstormHttpBridge_getSavedIdentity_Params_List is a list of SandstormHttpBridge_getSavedIdentity_Params.
type SandstormHttpBridge_getSavedIdentity_Params_List = capnp.StructList[SandstormHttpBridge_getSavedIdentity_Params]

// NewSandstormHttpBridge_getSavedIdentity_Params creates a new list of SandstormHttpBridge_getSavedIdentity_Params.
func NewSandstormHttpBridge_getSavedIdentity_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSavedIdentity_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSavedIdentity_Params](l), err
}

// SandstormHttpBridge_getSavedIdentity_Params_Future is a wrapper for a SandstormHttpBridge_getSavedIdentity_Params promised by a client call.
type SandstormHttpBridge_getSavedIdentity_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSavedIdentity_Params_Future) Struct() (SandstormHttpBridge_getSavedIdentity_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSavedIdentity_Params(s), err
}

type SandstormHttpBridge_getSavedIdentity_Results capnp.Struct

// SandstormHttpBridge_getSavedIdentity_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSavedIdentity_Results.
const SandstormHttpBridge_getSavedIdentity_Results_TypeID = 0xc2ba6a7e9ab2e369

func NewSandstormHttpBridge_getSavedIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results(st), err
}

func NewRootSandstormHttpBridge_getSavedIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSavedIdentity_Results(st), err
}

func ReadRootSandstormHttpBridge_getSavedIdentity_Results(msg *capnp.Message) (SandstormHttpBridge_getSavedIdentity_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSavedIdentity_Results(root.Struct()), err
}

func (s SandstormHttpBridge_getSavedIdentity_Results) String() string {
	str, _ := text.Marshal(0xc2ba6a7e9ab2e369, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSavedIdentity_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSavedIdentity_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSavedIdentity_Results {
	return SandstormHttpBridge_getSavedIdentity_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSavedIdentity_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSavedIdentity_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSavedIdentity_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSavedIdentity_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSavedIdentity_Results) Identity() identity.Identity {
	p, _ := capnp.Struct(s).Ptr(0)
	return identity.Identity(p.Interface().Client())
}

func (s SandstormHttpBridge_getSavedIdentity_Results) HasIdentity() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSavedIdentity_Results) SetIdentity(v identity.Identity) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_getSavedIdentity_Results_List is a list of SandstormHttpBridge_getSavedIdentity_Results.
type SandstormHttpBridge_getSavedIdentity_Results_List = capnp.StructList[SandstormHttpBridge_getSavedIdentity_Results]

// NewSandstormHttpBridge_getSavedIdentity_Results creates a new list of SandstormHttpBridge_getSavedIdentity_Results.
func NewSandstormHttpBridge_getSavedIdentity_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSavedIdentity_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSavedIdentity_Results](l), err
}

// SandstormHttpBridge_getSavedIdentity_Results_Future is a wrapper for a SandstormHttpBridge_getSavedIdentity_Results promised by a client call.
type SandstormHttpBridge_getSavedIdentity_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSavedIdentity_Results_Future) Struct() (SandstormHttpBridge_getSavedIdentity_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSavedIdentity_Results(s), err
}

func (p SandstormHttpBridge_getSavedIdentity_Results_Future) Identity() identity.Identity {
	return identity.Identity(p.Future.Field(0, nil).Client())
}

type SandstormHttpBridge_saveIdentity_Params capnp.Struct

// SandstormHttpBridge_saveIdentity_Params_TypeID is the unique identifier for the type SandstormHttpBridge_saveIdentity_Params.
const SandstormHttpBridge_saveIdentity_Params_TypeID = 0xd274ecd8fd2907d0

func NewSandstormHttpBridge_saveIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_saveIdentity_Params(st), err
}

func NewRootSandstormHttpBridge_saveIdentity_Params(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_saveIdentity_Params(st), err
}

func ReadRootSandstormHttpBridge_saveIdentity_Params(msg *capnp.Message) (SandstormHttpBridge_saveIdentity_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_saveIdentity_Params(root.Struct()), err
}

func (s SandstormHttpBridge_saveIdentity_Params) String() string {
	str, _ := text.Marshal(0xd274ecd8fd2907d0, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_saveIdentity_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_saveIdentity_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_saveIdentity_Params {
	return SandstormHttpBridge_saveIdentity_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_saveIdentity_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_saveIdentity_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_saveIdentity_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_saveIdentity_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_saveIdentity_Params) Identity() identity.Identity {
	p, _ := capnp.Struct(s).Ptr(0)
	return identity.Identity(p.Interface().Client())
}

func (s SandstormHttpBridge_saveIdentity_Params) HasIdentity() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_saveIdentity_Params) SetIdentity(v identity.Identity) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// SandstormHttpBridge_saveIdentity_Params_List is a list of SandstormHttpBridge_saveIdentity_Params.
type SandstormHttpBridge_saveIdentity_Params_List = capnp.StructList[SandstormHttpBridge_saveIdentity_Params]

// NewSandstormHttpBridge_saveIdentity_Params creates a new list of SandstormHttpBridge_saveIdentity_Params.
func NewSandstormHttpBridge_saveIdentity_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_saveIdentity_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_saveIdentity_Params](l), err
}

// SandstormHttpBridge_saveIdentity_Params_Future is a wrapper for a SandstormHttpBridge_saveIdentity_Params promised by a client call.
type SandstormHttpBridge_saveIdentity_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_saveIdentity_Params_Future) Struct() (SandstormHttpBridge_saveIdentity_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_saveIdentity_Params(s), err
}

func (p SandstormHttpBridge_saveIdentity_Params_Future) Identity() identity.Identity {
	return identity.Identity(p.Future.Field(0, nil).Client())
}

type SandstormHttpBridge_saveIdentity_Results capnp.Struct

// SandstormHttpBridge_saveIdentity_Results_TypeID is the unique identifier for the type SandstormHttpBridge_saveIdentity_Results.
const SandstormHttpBridge_saveIdentity_Results_TypeID = 0xb1b610269c6a2190

func NewSandstormHttpBridge_saveIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results(st), err
}

func NewRootSandstormHttpBridge_saveIdentity_Results(s *capnp.Segment) (SandstormHttpBridge_saveIdentity_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SandstormHttpBridge_saveIdentity_Results(st), err
}

func ReadRootSandstormHttpBridge_saveIdentity_Results(msg *capnp.Message) (SandstormHttpBridge_saveIdentity_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_saveIdentity_Results(root.Struct()), err
}

func (s SandstormHttpBridge_saveIdentity_Results) String() string {
	str, _ := text.Marshal(0xb1b610269c6a2190, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_saveIdentity_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_saveIdentity_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_saveIdentity_Results {
	return SandstormHttpBridge_saveIdentity_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_saveIdentity_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_saveIdentity_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_saveIdentity_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_saveIdentity_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// SandstormHttpBridge_saveIdentity_Results_List is a list of SandstormHttpBridge_saveIdentity_Results.
type SandstormHttpBridge_saveIdentity_Results_List = capnp.StructList[SandstormHttpBridge_saveIdentity_Results]

// NewSandstormHttpBridge_saveIdentity_Results creates a new list of SandstormHttpBridge_saveIdentity_Results.
func NewSandstormHttpBridge_saveIdentity_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_saveIdentity_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[SandstormHttpBridge_saveIdentity_Results](l), err
}

// SandstormHttpBridge_saveIdentity_Results_Future is a wrapper for a SandstormHttpBridge_saveIdentity_Results promised by a client call.
type SandstormHttpBridge_saveIdentity_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_saveIdentity_Results_Future) Struct() (SandstormHttpBridge_saveIdentity_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_saveIdentity_Results(s), err
}

type SandstormHttpBridge_getSessionRequest_Params capnp.Struct

// SandstormHttpBridge_getSessionRequest_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionRequest_Params.
const SandstormHttpBridge_getSessionRequest_Params_TypeID = 0xee4b3bf929955f83

func NewSandstormHttpBridge_getSessionRequest_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionRequest_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionRequest_Params(st), err
}

func NewRootSandstormHttpBridge_getSessionRequest_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionRequest_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionRequest_Params(st), err
}

func ReadRootSandstormHttpBridge_getSessionRequest_Params(msg *capnp.Message) (SandstormHttpBridge_getSessionRequest_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionRequest_Params(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionRequest_Params) String() string {
	str, _ := text.Marshal(0xee4b3bf929955f83, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionRequest_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionRequest_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionRequest_Params {
	return SandstormHttpBridge_getSessionRequest_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionRequest_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionRequest_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionRequest_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionRequest_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionRequest_Params) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSessionRequest_Params) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionRequest_Params) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSessionRequest_Params) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// SandstormHttpBridge_getSessionRequest_Params_List is a list of SandstormHttpBridge_getSessionRequest_Params.
type SandstormHttpBridge_getSessionRequest_Params_List = capnp.StructList[SandstormHttpBridge_getSessionRequest_Params]

// NewSandstormHttpBridge_getSessionRequest_Params creates a new list of SandstormHttpBridge_getSessionRequest_Params.
func NewSandstormHttpBridge_getSessionRequest_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionRequest_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionRequest_Params](l), err
}

// SandstormHttpBridge_getSessionRequest_Params_Future is a wrapper for a SandstormHttpBridge_getSessionRequest_Params promised by a client call.
type SandstormHttpBridge_getSessionRequest_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionRequest_Params_Future) Struct() (SandstormHttpBridge_getSessionRequest_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionRequest_Params(s), err
}

type SandstormHttpBridge_getSessionRequest_Results capnp.Struct

// SandstormHttpBridge_getSessionRequest_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionRequest_Results.
const SandstormHttpBridge_getSessionRequest_Results_TypeID = 0xb2e5439feb5f31ce

func NewSandstormHttpBridge_getSessionRequest_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionRequest_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionRequest_Results(st), err
}

func NewRootSandstormHttpBridge_getSessionRequest_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionRequest_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionRequest_Results(st), err
}

func ReadRootSandstormHttpBridge_getSessionRequest_Results(msg *capnp.Message) (SandstormHttpBridge_getSessionRequest_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionRequest_Results(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionRequest_Results) String() string {
	str, _ := text.Marshal(0xb2e5439feb5f31ce, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionRequest_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionRequest_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionRequest_Results {
	return SandstormHttpBridge_getSessionRequest_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionRequest_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionRequest_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionRequest_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionRequest_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionRequest_Results) RequestInfo() (powerbox.PowerboxDescriptor_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return powerbox.PowerboxDescriptor_List(p.List()), err
}

func (s SandstormHttpBridge_getSessionRequest_Results) HasRequestInfo() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionRequest_Results) SetRequestInfo(v powerbox.PowerboxDescriptor_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewRequestInfo sets the requestInfo field to a newly
// allocated powerbox.PowerboxDescriptor_List, preferring placement in s's segment.
func (s SandstormHttpBridge_getSessionRequest_Results) NewRequestInfo(n int32) (powerbox.PowerboxDescriptor_List, error) {
	l, err := powerbox.NewPowerboxDescriptor_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return powerbox.PowerboxDescriptor_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// SandstormHttpBridge_getSessionRequest_Results_List is a list of SandstormHttpBridge_getSessionRequest_Results.
type SandstormHttpBridge_getSessionRequest_Results_List = capnp.StructList[SandstormHttpBridge_getSessionRequest_Results]

// NewSandstormHttpBridge_getSessionRequest_Results creates a new list of SandstormHttpBridge_getSessionRequest_Results.
func NewSandstormHttpBridge_getSessionRequest_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionRequest_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionRequest_Results](l), err
}

// SandstormHttpBridge_getSessionRequest_Results_Future is a wrapper for a SandstormHttpBridge_getSessionRequest_Results promised by a client call.
type SandstormHttpBridge_getSessionRequest_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionRequest_Results_Future) Struct() (SandstormHttpBridge_getSessionRequest_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionRequest_Results(s), err
}

type SandstormHttpBridge_getSessionOffer_Params capnp.Struct

// SandstormHttpBridge_getSessionOffer_Params_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionOffer_Params.
const SandstormHttpBridge_getSessionOffer_Params_TypeID = 0xd7dfe01ad496e65c

func NewSandstormHttpBridge_getSessionOffer_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionOffer_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionOffer_Params(st), err
}

func NewRootSandstormHttpBridge_getSessionOffer_Params(s *capnp.Segment) (SandstormHttpBridge_getSessionOffer_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SandstormHttpBridge_getSessionOffer_Params(st), err
}

func ReadRootSandstormHttpBridge_getSessionOffer_Params(msg *capnp.Message) (SandstormHttpBridge_getSessionOffer_Params, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionOffer_Params(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionOffer_Params) String() string {
	str, _ := text.Marshal(0xd7dfe01ad496e65c, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionOffer_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionOffer_Params) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionOffer_Params {
	return SandstormHttpBridge_getSessionOffer_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionOffer_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionOffer_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionOffer_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionOffer_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionOffer_Params) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SandstormHttpBridge_getSessionOffer_Params) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionOffer_Params) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SandstormHttpBridge_getSessionOffer_Params) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// SandstormHttpBridge_getSessionOffer_Params_List is a list of SandstormHttpBridge_getSessionOffer_Params.
type SandstormHttpBridge_getSessionOffer_Params_List = capnp.StructList[SandstormHttpBridge_getSessionOffer_Params]

// NewSandstormHttpBridge_getSessionOffer_Params creates a new list of SandstormHttpBridge_getSessionOffer_Params.
func NewSandstormHttpBridge_getSessionOffer_Params_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionOffer_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionOffer_Params](l), err
}

// SandstormHttpBridge_getSessionOffer_Params_Future is a wrapper for a SandstormHttpBridge_getSessionOffer_Params promised by a client call.
type SandstormHttpBridge_getSessionOffer_Params_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionOffer_Params_Future) Struct() (SandstormHttpBridge_getSessionOffer_Params, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionOffer_Params(s), err
}

type SandstormHttpBridge_getSessionOffer_Results capnp.Struct

// SandstormHttpBridge_getSessionOffer_Results_TypeID is the unique identifier for the type SandstormHttpBridge_getSessionOffer_Results.
const SandstormHttpBridge_getSessionOffer_Results_TypeID = 0xf38a4e91679a53d1

func NewSandstormHttpBridge_getSessionOffer_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionOffer_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SandstormHttpBridge_getSessionOffer_Results(st), err
}

func NewRootSandstormHttpBridge_getSessionOffer_Results(s *capnp.Segment) (SandstormHttpBridge_getSessionOffer_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SandstormHttpBridge_getSessionOffer_Results(st), err
}

func ReadRootSandstormHttpBridge_getSessionOffer_Results(msg *capnp.Message) (SandstormHttpBridge_getSessionOffer_Results, error) {
	root, err := msg.Root()
	return SandstormHttpBridge_getSessionOffer_Results(root.Struct()), err
}

func (s SandstormHttpBridge_getSessionOffer_Results) String() string {
	str, _ := text.Marshal(0xf38a4e91679a53d1, capnp.Struct(s))
	return str
}

func (s SandstormHttpBridge_getSessionOffer_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SandstormHttpBridge_getSessionOffer_Results) DecodeFromPtr(p capnp.Ptr) SandstormHttpBridge_getSessionOffer_Results {
	return SandstormHttpBridge_getSessionOffer_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SandstormHttpBridge_getSessionOffer_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SandstormHttpBridge_getSessionOffer_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SandstormHttpBridge_getSessionOffer_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SandstormHttpBridge_getSessionOffer_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SandstormHttpBridge_getSessionOffer_Results) Offer() capnp.Client {
	p, _ := capnp.Struct(s).Ptr(0)
	return p.Interface().Client()
}

func (s SandstormHttpBridge_getSessionOffer_Results) HasOffer() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SandstormHttpBridge_getSessionOffer_Results) SetOffer(c capnp.Client) error {
	if !c.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(c))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}
func (s SandstormHttpBridge_getSessionOffer_Results) Descriptor() (powerbox.PowerboxDescriptor, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return powerbox.PowerboxDescriptor(p.Struct()), err
}

func (s SandstormHttpBridge_getSessionOffer_Results) HasDescriptor() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SandstormHttpBridge_getSessionOffer_Results) SetDescriptor(v powerbox.PowerboxDescriptor) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewDescriptor sets the descriptor field to a newly
// allocated powerbox.PowerboxDescriptor struct, preferring placement in s's segment.
func (s SandstormHttpBridge_getSessionOffer_Results) NewDescriptor() (powerbox.PowerboxDescriptor, error) {
	ss, err := powerbox.NewPowerboxDescriptor(capnp.Struct(s).Segment())
	if err != nil {
		return powerbox.PowerboxDescriptor{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// SandstormHttpBridge_getSessionOffer_Results_List is a list of SandstormHttpBridge_getSessionOffer_Results.
type SandstormHttpBridge_getSessionOffer_Results_List = capnp.StructList[SandstormHttpBridge_getSessionOffer_Results]

// NewSandstormHttpBridge_getSessionOffer_Results creates a new list of SandstormHttpBridge_getSessionOffer_Results.
func NewSandstormHttpBridge_getSessionOffer_Results_List(s *capnp.Segment, sz int32) (SandstormHttpBridge_getSessionOffer_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[SandstormHttpBridge_getSessionOffer_Results](l), err
}

// SandstormHttpBridge_getSessionOffer_Results_Future is a wrapper for a SandstormHttpBridge_getSessionOffer_Results promised by a client call.
type SandstormHttpBridge_getSessionOffer_Results_Future struct{ *capnp.Future }

func (p SandstormHttpBridge_getSessionOffer_Results_Future) Struct() (SandstormHttpBridge_getSessionOffer_Results, error) {
	s, err := p.Future.Struct()
	return SandstormHttpBridge_getSessionOffer_Results(s), err
}

func (p SandstormHttpBridge_getSessionOffer_Results_Future) Offer() *capnp.Future {
	return p.Future.Field(0, nil)
}

func (p SandstormHttpBridge_getSessionOffer_Results_Future) Descriptor() powerbox.PowerboxDescriptor_Future {
	return powerbox.PowerboxDescriptor_Future{Future: p.Future.Field(1, nil)}
}

type AppHooks capnp.Client

// AppHooks_TypeID is the unique identifier for the type AppHooks.
const AppHooks_TypeID = 0xcb12390f1429f70f

func (c AppHooks) GetViewInfo(ctx context.Context, params func(AppHooks_getViewInfo_Params) error) (grain.UiView_ViewInfo_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "getViewInfo",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AppHooks_getViewInfo_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return grain.UiView_ViewInfo_Future{Future: ans.Future()}, release
}
func (c AppHooks) Restore(ctx context.Context, params func(AppHooks_restore_Params) error) (AppHooks_restore_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "restore",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AppHooks_restore_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AppHooks_restore_Results_Future{Future: ans.Future()}, release
}
func (c AppHooks) Drop(ctx context.Context, params func(AppHooks_drop_Params) error) (AppHooks_drop_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "drop",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AppHooks_drop_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AppHooks_drop_Results_Future{Future: ans.Future()}, release
}

func (c AppHooks) AddRef() AppHooks {
	return AppHooks(capnp.Client(c).AddRef())
}

func (c AppHooks) Release() {
	capnp.Client(c).Release()
}

func (c AppHooks) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (AppHooks) DecodeFromPtr(p capnp.Ptr) AppHooks {
	return AppHooks(capnp.Client{}.DecodeFromPtr(p))
}

func (c AppHooks) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// A AppHooks_Server is a AppHooks with a local implementation.
type AppHooks_Server interface {
	GetViewInfo(context.Context, AppHooks_getViewInfo) error

	Restore(context.Context, AppHooks_restore) error

	Drop(context.Context, AppHooks_drop) error
}

// AppHooks_NewServer creates a new Server from an implementation of AppHooks_Server.
func AppHooks_NewServer(s AppHooks_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(AppHooks_Methods(nil, s), s, c)
}

// AppHooks_ServerToClient creates a new Client from an implementation of AppHooks_Server.
// The caller is responsible for calling Release on the returned Client.
func AppHooks_ServerToClient(s AppHooks_Server) AppHooks {
	return AppHooks(capnp.NewClient(AppHooks_NewServer(s)))
}

// AppHooks_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func AppHooks_Methods(methods []server.Method, s AppHooks_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      0,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "getViewInfo",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetViewInfo(ctx, AppHooks_getViewInfo{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      1,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "restore",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Restore(ctx, AppHooks_restore{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xcb12390f1429f70f,
			MethodID:      2,
			InterfaceName: "sandstorm-http-bridge.capnp:AppHooks",
			MethodName:    "drop",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Drop(ctx, AppHooks_drop{call})
		},
	})

	return methods
}

// AppHooks_getViewInfo holds the state for a server call to AppHooks.getViewInfo.
// See server.Call for documentation.
type AppHooks_getViewInfo struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AppHooks_getViewInfo) Args() AppHooks_getViewInfo_Params {
	return AppHooks_getViewInfo_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AppHooks_getViewInfo) AllocResults() (grain.UiView_ViewInfo, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 8})
	return grain.UiView_ViewInfo(r), err
}

// AppHooks_restore holds the state for a server call to AppHooks.restore.
// See server.Call for documentation.
type AppHooks_restore struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AppHooks_restore) Args() AppHooks_restore_Params {
	return AppHooks_restore_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AppHooks_restore) AllocResults() (AppHooks_restore_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_restore_Results(r), err
}

// AppHooks_drop holds the state for a server call to AppHooks.drop.
// See server.Call for documentation.
type AppHooks_drop struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AppHooks_drop) Args() AppHooks_drop_Params {
	return AppHooks_drop_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AppHooks_drop) AllocResults() (AppHooks_drop_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AppHooks_drop_Results(r), err
}

// AppHooks_List is a list of AppHooks.
type AppHooks_List = capnp.CapList[AppHooks]

// NewAppHooks creates a new list of AppHooks.
func NewAppHooks_List(s *capnp.Segment, sz int32) (AppHooks_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[AppHooks](l), err
}

type AppHooks_getViewInfo_Params capnp.Struct

// AppHooks_getViewInfo_Params_TypeID is the unique identifier for the type AppHooks_getViewInfo_Params.
const AppHooks_getViewInfo_Params_TypeID = 0xd70d957bcd120795

func NewAppHooks_getViewInfo_Params(s *capnp.Segment) (AppHooks_getViewInfo_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AppHooks_getViewInfo_Params(st), err
}

func NewRootAppHooks_getViewInfo_Params(s *capnp.Segment) (AppHooks_getViewInfo_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AppHooks_getViewInfo_Params(st), err
}

func ReadRootAppHooks_getViewInfo_Params(msg *capnp.Message) (AppHooks_getViewInfo_Params, error) {
	root, err := msg.Root()
	return AppHooks_getViewInfo_Params(root.Struct()), err
}

func (s AppHooks_getViewInfo_Params) String() string {
	str, _ := text.Marshal(0xd70d957bcd120795, capnp.Struct(s))
	return str
}

func (s AppHooks_getViewInfo_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AppHooks_getViewInfo_Params) DecodeFromPtr(p capnp.Ptr) AppHooks_getViewInfo_Params {
	return AppHooks_getViewInfo_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AppHooks_getViewInfo_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AppHooks_getViewInfo_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AppHooks_getViewInfo_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AppHooks_getViewInfo_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AppHooks_getViewInfo_Params_List is a list of AppHooks_getViewInfo_Params.
type AppHooks_getViewInfo_Params_List = capnp.StructList[AppHooks_getViewInfo_Params]

// NewAppHooks_getViewInfo_Params creates a new list of AppHooks_getViewInfo_Params.
func NewAppHooks_getViewInfo_Params_List(s *capnp.Segment, sz int32) (AppHooks_getViewInfo_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AppHooks_getViewInfo_Params](l), err
}

// AppHooks_getViewInfo_Params_Future is a wrapper for a AppHooks_getViewInfo_Params promised by a client call.
type AppHooks_getViewInfo_Params_Future struct{ *capnp.Future }

func (p AppHooks_getViewInfo_Params_Future) Struct() (AppHooks_getViewInfo_Params, error) {
	s, err := p.Future.Struct()
	return AppHooks_getViewInfo_Params(s), err
}

type AppHooks_restore_Params capnp.Struct

// AppHooks_restore_Params_TypeID is the unique identifier for the type AppHooks_restore_Params.
const AppHooks_restore_Params_TypeID = 0xd7ba83f0808259c3

func NewAppHooks_restore_Params(s *capnp.Segment) (AppHooks_restore_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_restore_Params(st), err
}

func NewRootAppHooks_restore_Params(s *capnp.Segment) (AppHooks_restore_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_restore_Params(st), err
}

func ReadRootAppHooks_restore_Params(msg *capnp.Message) (AppHooks_restore_Params, error) {
	root, err := msg.Root()
	return AppHooks_restore_Params(root.Struct()), err
}

func (s AppHooks_restore_Params) String() string {
	str, _ := text.Marshal(0xd7ba83f0808259c3, capnp.Struct(s))
	return str
}

func (s AppHooks_restore_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AppHooks_restore_Params) DecodeFromPtr(p capnp.Ptr) AppHooks_restore_Params {
	return AppHooks_restore_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AppHooks_restore_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AppHooks_restore_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AppHooks_restore_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AppHooks_restore_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AppHooks_restore_Params) ObjectId() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(0)
}

func (s AppHooks_restore_Params) HasObjectId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AppHooks_restore_Params) SetObjectId(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(0, v)
}

// AppHooks_restore_Params_List is a list of AppHooks_restore_Params.
type AppHooks_restore_Params_List = capnp.StructList[AppHooks_restore_Params]

// NewAppHooks_restore_Params creates a new list of AppHooks_restore_Params.
func NewAppHooks_restore_Params_List(s *capnp.Segment, sz int32) (AppHooks_restore_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AppHooks_restore_Params](l), err
}

// AppHooks_restore_Params_Future is a wrapper for a AppHooks_restore_Params promised by a client call.
type AppHooks_restore_Params_Future struct{ *capnp.Future }

func (p AppHooks_restore_Params_Future) Struct() (AppHooks_restore_Params, error) {
	s, err := p.Future.Struct()
	return AppHooks_restore_Params(s), err
}

func (p AppHooks_restore_Params_Future) ObjectId() *capnp.Future {
	return p.Future.Field(0, nil)
}

type AppHooks_restore_Results capnp.Struct

// AppHooks_restore_Results_TypeID is the unique identifier for the type AppHooks_restore_Results.
const AppHooks_restore_Results_TypeID = 0xf4bee520c5eef2bc

func NewAppHooks_restore_Results(s *capnp.Segment) (AppHooks_restore_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_restore_Results(st), err
}

func NewRootAppHooks_restore_Results(s *capnp.Segment) (AppHooks_restore_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_restore_Results(st), err
}

func ReadRootAppHooks_restore_Results(msg *capnp.Message) (AppHooks_restore_Results, error) {
	root, err := msg.Root()
	return AppHooks_restore_Results(root.Struct()), err
}

func (s AppHooks_restore_Results) String() string {
	str, _ := text.Marshal(0xf4bee520c5eef2bc, capnp.Struct(s))
	return str
}

func (s AppHooks_restore_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AppHooks_restore_Results) DecodeFromPtr(p capnp.Ptr) AppHooks_restore_Results {
	return AppHooks_restore_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AppHooks_restore_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AppHooks_restore_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AppHooks_restore_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AppHooks_restore_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AppHooks_restore_Results) Cap() capnp.Client {
	p, _ := capnp.Struct(s).Ptr(0)
	return p.Interface().Client()
}

func (s AppHooks_restore_Results) HasCap() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AppHooks_restore_Results) SetCap(c capnp.Client) error {
	if !c.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(c))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// AppHooks_restore_Results_List is a list of AppHooks_restore_Results.
type AppHooks_restore_Results_List = capnp.StructList[AppHooks_restore_Results]

// NewAppHooks_restore_Results creates a new list of AppHooks_restore_Results.
func NewAppHooks_restore_Results_List(s *capnp.Segment, sz int32) (AppHooks_restore_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AppHooks_restore_Results](l), err
}

// AppHooks_restore_Results_Future is a wrapper for a AppHooks_restore_Results promised by a client call.
type AppHooks_restore_Results_Future struct{ *capnp.Future }

func (p AppHooks_restore_Results_Future) Struct() (AppHooks_restore_Results, error) {
	s, err := p.Future.Struct()
	return AppHooks_restore_Results(s), err
}

func (p AppHooks_restore_Results_Future) Cap() *capnp.Future {
	return p.Future.Field(0, nil)
}

type AppHooks_drop_Params capnp.Struct

// AppHooks_drop_Params_TypeID is the unique identifier for the type AppHooks_drop_Params.
const AppHooks_drop_Params_TypeID = 0xc2aaaaa69f8230cc

func NewAppHooks_drop_Params(s *capnp.Segment) (AppHooks_drop_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_drop_Params(st), err
}

func NewRootAppHooks_drop_Params(s *capnp.Segment) (AppHooks_drop_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AppHooks_drop_Params(st), err
}

func ReadRootAppHooks_drop_Params(msg *capnp.Message) (AppHooks_drop_Params, error) {
	root, err := msg.Root()
	return AppHooks_drop_Params(root.Struct()), err
}

func (s AppHooks_drop_Params) String() string {
	str, _ := text.Marshal(0xc2aaaaa69f8230cc, capnp.Struct(s))
	return str
}

func (s AppHooks_drop_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AppHooks_drop_Params) DecodeFromPtr(p capnp.Ptr) AppHooks_drop_Params {
	return AppHooks_drop_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AppHooks_drop_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AppHooks_drop_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AppHooks_drop_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AppHooks_drop_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AppHooks_drop_Params) ObjectId() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(0)
}

func (s AppHooks_drop_Params) HasObjectId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AppHooks_drop_Params) SetObjectId(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(0, v)
}

// AppHooks_drop_Params_List is a list of AppHooks_drop_Params.
type AppHooks_drop_Params_List = capnp.StructList[AppHooks_drop_Params]

// NewAppHooks_drop_Params creates a new list of AppHooks_drop_Params.
func NewAppHooks_drop_Params_List(s *capnp.Segment, sz int32) (AppHooks_drop_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AppHooks_drop_Params](l), err
}

// AppHooks_drop_Params_Future is a wrapper for a AppHooks_drop_Params promised by a client call.
type AppHooks_drop_Params_Future struct{ *capnp.Future }

func (p AppHooks_drop_Params_Future) Struct() (AppHooks_drop_Params, error) {
	s, err := p.Future.Struct()
	return AppHooks_drop_Params(s), err
}

func (p AppHooks_drop_Params_Future) ObjectId() *capnp.Future {
	return p.Future.Field(0, nil)
}

type AppHooks_drop_Results capnp.Struct

// AppHooks_drop_Results_TypeID is the unique identifier for the type AppHooks_drop_Results.
const AppHooks_drop_Results_TypeID = 0x9439551d1ee49012

func NewAppHooks_drop_Results(s *capnp.Segment) (AppHooks_drop_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AppHooks_drop_Results(st), err
}

func NewRootAppHooks_drop_Results(s *capnp.Segment) (AppHooks_drop_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AppHooks_drop_Results(st), err
}

func ReadRootAppHooks_drop_Results(msg *capnp.Message) (AppHooks_drop_Results, error) {
	root, err := msg.Root()
	return AppHooks_drop_Results(root.Struct()), err
}

func (s AppHooks_drop_Results) String() string {
	str, _ := text.Marshal(0x9439551d1ee49012, capnp.Struct(s))
	return str
}

func (s AppHooks_drop_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AppHooks_drop_Results) DecodeFromPtr(p capnp.Ptr) AppHooks_drop_Results {
	return AppHooks_drop_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AppHooks_drop_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AppHooks_drop_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AppHooks_drop_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AppHooks_drop_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AppHooks_drop_Results_List is a list of AppHooks_drop_Results.
type AppHooks_drop_Results_List = capnp.StructList[AppHooks_drop_Results]

// NewAppHooks_drop_Results creates a new list of AppHooks_drop_Results.
func NewAppHooks_drop_Results_List(s *capnp.Segment, sz int32) (AppHooks_drop_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AppHooks_drop_Results](l), err
}

// AppHooks_drop_Results_Future is a wrapper for a AppHooks_drop_Results promised by a client call.
type AppHooks_drop_Results_Future struct{ *capnp.Future }

func (p AppHooks_drop_Results_Future) Struct() (AppHooks_drop_Results, error) {
	s, err := p.Future.Struct()
	return AppHooks_drop_Results(s), err
}

const schema_ac137d236832bb1e = "x\xda\xa4V_L\x1c\xd5\x17>gf\xf77\xfc\x12" +
	"\xd6\xe5\xb2}X\x96\xddV+\xfe\x81H\xb3\x94h(" +
	"\x8d\xc2\xd2\x07\xbbhd\x07\xa2\x91\x06m\x96\x9d\x81\x0e" +
	"\xc2\xce\xb83\xb4\xa2b+\x95\x1aH\x1a\xb1\x16c\x1b" +
	"\x0d\x89UcI\xfb\xd0>\x18S\x8b(\x864M\xd5" +
	"\xda\xa6\x11y0\x9aX\x9a\x18mc\xac\x89)\x09\x8e" +
	"\xb93{\x87\x81\x00\x96%\xfb\xb4\xf7~\xe7\x9c\xef\xfc" +
	"\xfb\xeeD\xa3y\xb5\x9e\x0a\xdfT\x14\xb8\xa6*\xce\xfb" +
	"?S\x9a\x94F&\x87\xae\x1c\x00\x12E\x00\x8f\x00P" +
	")\x06\xab9\xf0\x98\xe3\x07^>\x8c}\xbe\xb7\xec\x1b" +
	"/\xd2\xabx\xb0\x8e\x03\x0c$\x835\x80f\xe1\xd0\xd5" +
	"\xf5\x91'\xb7\x1c\x06r\x8feZ\x80\x95\xfd\xc1C\x08" +
	"\x1espz\xec\xff\xbe7\xdaO\x02\x09\xf3\xe6\xfa\xcf" +
	"6\xef\xba\xbb7p\x02\x00+\xbb\x83}\x18\x18\x08R" +
	"W\xfd\xc1\xd71p\xa4H\x000\x87\xee\xeax\xf7\xde" +
	"\x82ON\xb98\xbcZTF9|[\xb1\xf3\xb7\x91" +
	"m3\xa7\xdd\x1cz\x8a\x1a)\x87\xe1\"\xcaa\xec\xe0" +
	"\xd5\x8d\x95\xb3\x0d\x9f\xba\x01\xe7m\xc0\x8c\x058\x11\xff" +
	"~\xeb}\xff\x18_\xba\x01\xde\x90\x95E$D\x01\xb3" +
	"\xc7RU\xb3\xfb>\x98p\x03\x1e\x0e\xd5S@\xb3\x05" +
	"\xf8:\xda7\xf2\xd1\xe8\xe8\x84\x9d\xa6\x17i\x9e=\xa1" +
	"A\x04\x0c\x0cX\x00\xe5\x97\xd3G_\xe98\xb3\xc0\xc3" +
	"I\xdb\xc3y\x0b\xe0\xff\xbbt\x9d\x7fK\xe1\x85E\xe5" +
	"\x80\x02\xac\xbc\x1e*\xc3\xc0\\H\x00\x08\xdc\x0a\x9d\x0b" +
	"L\x17\x0b\x81\xe9b\xbf\xf9\x9dP:\xf7\xc3\xef\xc6e" +
	"\xb7\xcbK\xc5\x1b\xa9\xcb_\x8b\xa9\xcba\xa1\xf0\x9b\x97" +
	"\x86}S\xae\xda\xfb\xc2\x13\xb4\xf6_5\xf7\xed\xfbc" +
	"\xff\x99)7\xdd\xb9\xe2\xf7)]_\x98\x9a\xb6\\{" +
	"\xfbJ\xe8\xe7\x9f\xa6\xdc\xbe+\xc2\xd5\xd4w\xdc\x02\xec" +
	"\xdf9\\zk\xebc7\xdc\x00%l\xe5\xd3o\x01" +
	".5\x1dm\x7f\xf3\x89\xc1\x9bY\x00G\x01\x1f\x86\xad" +
	"\x9a\x8e\x85\xf7\x00\x9ag\xff\xbc1y\xe7\xcc\xe7\x7f\xb9" +
	"9D\"\xa3\x94Cy\xa4\x06L\xe7Wo\xea\xc9\xb4" +
	"\xa4\x1bjF\xe8*\xdfe\x18ZykF\x91\xda\xe5" +
	"M\xa9\xa4\x96\xd6\xaa\x9b\xb2\x97]\xdb\x0dC\xab\xb3o" +
	"\xdae\xc39\x8eiJIM\"\x99Iv\xe9\x8e\xa3" +
	"\xbcU9\xda-KqIN\x1b\x8a\xd1Sb;\x02" +
	"\xd1\xc3{\x00<\x08@|;\x00\xc4|\x1e\xc5 \x87" +
	"\xa6\x92\xc5\x01\x1f\x970\x1f8\xcc\x07t\xa2z\x97\x8a" +
	"\x1a\xd3\xb4\xed\xaa\xfa\x9c\xbeI\xca\xa8ZI\xa3\xacw" +
	"w\x1a\xa8\xafl\xb3\x04SH \x8aA\xde\x0b\xe0l" +
	"+\xb2\xb1&\xa7\xfa\x80#\xc7\x05\x9c\x1fdd;A" +
	"\xde;\x04\x1c9\"\xe0\xfc.#\x9bUrp\x108" +
	"2 \xa0\xd7\x995dkHz;\x80#\xdd\x02r" +
	"\xce( [D\xa2P\x9f\xb2\x80\xbc3G\xc8\xc6\x81" +
	"4S.\xa2`\xb2\x16a\xb6GP\x8b\xd6\x99\xac\xeb" +
	"\x0a\xaa\xe9mj\xda\x90_@#{J{\x80\xac\x09" +
	"@\xb1zr\xb7L\x0f\xc0O\x8f\x16\x1a7\xca\xcfw" +
	"\xcb\xbac\x9c=mhk\x933P\x8b\x09\xc4\xd5O" +
	"\x14\x0bg\x0dA\xa3\xac\xfb\xbb;\x8d\x1c\xe7\x89\xd2a" +
	"\x1c\x0d\xa7\xe3\xee\x89j\xcdN\xd4\xfd\x1c\x9a\x19\x1b\x17" +
	"\x07!\xdd\xa6\xe2\x1d\x80\x09\x1e\xb1\xc0|:|n\xfc" +
	"\x98\xff\xe2u\x00\xa4\x87kab\x97zi&u\x00" +
	"b\x1e\x8f\xe2:\x0e\xf7\xa6l\x1c\x12\xf3\xa1\x9b\xa9\x1d" +
	"\x91\xdaG\xc6ip\x92kp\xf7~\xda\xa1\x17\xae\xd5" +
	"\xc6\xf9\xd0BRS\x90\x98\x178\xad\xecb\x83|y" +
	"Ma\x17\xe6\x9c]\xe7\x05\x81C\xf3\x81y%\xa7-" +
	"^\xcak\xbdK%\xd4\xd6\x0e9e\xc4%\x00\xc0B" +
	"ti?\xfd\x9fs=\xdd2\xc5\x0a\xba,\x05G\xa8" +
	"\x00\x90\x98\xc1\x1f\xc5\xe3/\xbe\xf3\xda\x17\x8b+\xcb/" +
	"\x97\xab\x9f&K%'\xdf\x92\x1c\xf6\xd2\xa0|\xed\xe3" +
	"\xd8\xa3\x0f>{\x96\x88\xad\x00\xb1\x04\x0d\xfb\x0c\xd5\x1d" +
	"\xf6\xe0 S}\"\xd6\x01\xc4\x1e\xc7X\x0b\x92.\xaa" +
	"\"\xec\x05E\xf6\xc5@\x92e\x00\xb1\x16\x8cu\"\xe9" +
	"\xb5\xf4\xe2)E\xdec\xef\x01\xc1\x0d\xa2\x87s\x15\x0e" +
	"\x91\x8a\xc2\xde\x8cLY\xcbK^/c\xe3\xa7\x1d[" +
	"\x8dA\x021\xe6A\x82\xadfL\xd3\x1ah'A0" +
	"\xe2\xd2\x1a%%\x91\xcc\x08\xc9.}m\xed\xca_q" +
	"4Y\x05\xd3m*\x9bPf\xb8\xa2]\xb6\xa8\xffE" +
	"\xf1v\x87ZX\xfd\xb6Z\xca\xcd\x1e\xf1U\xac\xea\x1a" +
	"d9\x07a\xc8\xcb51G\xfd\xf2\x9cX\xa5\x9b\x01" +
	"\xc4\x12\x1e\xc5(\x87\x04q\x9d5\x8f\xe5\xf4K\xe3\x01" +
	"\x1e\xc5*\x0e7\xa8\xd4\x14\x0b=<\xa0U^I\xd6" +
	"S\x19E3\x80W3\x8b\xde\x87\x82\xdbV/\xd6j" +
	"\xf6\xc0-\xa7\xc7\xa9\xa46\x1f\xfa\xdf\x00\x00\x00\xff\xff" +
	"\xda\x03\xb0\xc9"

func init() {
	schemas.Register(schema_ac137d236832bb1e,
		0x86d490c59f64c564,
		0x930d8201947c86bf,
		0x9439551d1ee49012,
		0xad678f0d09bdd98a,
		0xb1b610269c6a2190,
		0xb2e5439feb5f31ce,
		0xb84ffa3322e48dbd,
		0xc174fe273bd649ac,
		0xc2a480fa3863a3fa,
		0xc2aaaaa69f8230cc,
		0xc2ba6a7e9ab2e369,
		0xcb12390f1429f70f,
		0xd274ecd8fd2907d0,
		0xd70d957bcd120795,
		0xd7ba83f0808259c3,
		0xd7dfe01ad496e65c,
		0xee4b3bf929955f83,
		0xf38a4e91679a53d1,
		0xf4bee520c5eef2bc)
}
